services:
  - type: web
    name: inventory-app-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && node src/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 4000
